### ISSUE TITLE
Version 1.3.21 on PyPI does not have .mo files

### ISSUE THREAD

**Issue by abosio** [plone/Products.TinyMCE#149]
1.3.21 of this package as uploaded to PyPI is missing the *.mo translations files.

This causes no text labels for options in the link target select menu (and maybe other missing text elements).

**Comment by mauritsvanrees** [comment]
Strange: I released that version, plus a few more versions since then. I use zest.releaser to make the releases, and have this setup to compile po files. So it *should* work.

Argh! We need the zest.pocompile package for that, and I thought this was included in our setup, but it has not been for the past half year... :-( I did that myself in https://github.com/plone/buildout.coredev/commit/dccb5d52c5f5d625421a006442d2721ea53f13d8#diff-6b591431209f519103be7457c3f7cdeaL75

I have fixed it, so future versions will have the .mo files.

Meanwhile, lots of packages that you use will be missing .mo files, not just this one.  Several ways to fix that.

I have this in all my buildouts, to make sure the .mo files are compiled on startup:

    zope_i18n_compile_mo_files true

See http://docs.plone.org/develop/plone/i18n/internationalisation.html#i18ndude
The system user that you use to run Plone needs write access to the packages for this to function.

Alternatively, use [zest.pocompile](https://pypi.python.org/pypi/zest.pocompile). Install it in a virtualenv (or in your buildout), go to the `eggs` directory and run `pocompile`. This looks for all `locales` or `locale` directories, and compiles the `.po` files to `.mo` files. You can try it out in a single package directory first, if you want.
